### ISSUE TITLE
Question: cannot build front-end files

### ISSUE THREAD

**Issue by ffyuanda** [casbin/casdoor#240]
I'm on a Ubuntu 20.04 remote ssh, and I'm trying to build Casdoor following the README file.

The info after running `cd web/ && npm install && npm run start
`
```bash
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5 requires a peer of @babel/core@^7.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dom@17.0.2 requires a peer of react@17.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 2230 packages in 10.735s

151 packages are looking for funding
  run `npm fund` for details

found 3 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> web@0.1.0 build /root/go/casdoor/web
> craco build

Creating an optimized production build...

                    The build failed because the process exited too early.
                    This probably means the system ran out of memory or someone called
                    `kill -9` on the process.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.1.0 build: `craco build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-08T09_37_23_393Z-debug.log
```

The error log:
```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle web@0.1.0~prebuild: web@0.1.0
6 info lifecycle web@0.1.0~build: web@0.1.0
7 verbose lifecycle web@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle web@0.1.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/go/casdoor/web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle web@0.1.0~build: CWD: /root/go/casdoor/web
10 silly lifecycle web@0.1.0~build: Args: [ '-c', 'craco build' ]
11 silly lifecycle web@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle web@0.1.0~build: Failed to exec build script
13 verbose stack Error: web@0.1.0 build: `craco build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid web@0.1.0
15 verbose cwd /root/go/casdoor/web
16 verbose Linux 5.4.0-77-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error web@0.1.0 build: `craco build`
22 error Exit status 1
23 error Failed at the web@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Mysql is working correctly. I'm not sure why this happen, I was able to build it the first time, but I failed all the way here after the first build.

**Comment by sh1luo** [comment]
@ffyuanda hi, log has said very clearly:
```bash
Creating an optimized production build...

                    The build failed because the process exited too early.
                    This probably means the system ran out of memory or someone called
                    `kill -9` on the process.
```
I think it is most likely that your memory has run out.

**Comment by ffyuanda** [comment]
@sh1luo oops, I didn't think about the memory limit, thx I will check if it is the case.

**Comment by sh1luo** [comment]
@ffyuanda use `npm run build` instead, then visit `your ip:8000` after running your back-end program.

This way may work for you.

**Comment by ffyuanda** [comment]
@sh1luo I've tried `npm run build` but the same problem pops up. However I can `go run main.go` and the 8000 port is online, but without the front-end files, it simply prints out the `404` code

**Comment by ffyuanda** [comment]
I got a 2GB memory so that might be not enough?

**Comment by ErikQQY** [comment]
I have the same situation before, I think it is because the 2GB memory is not enough

**Comment by sh1luo** [comment]
> I have the same situation before, I think it is because the 2GB memory is not enough

You can execute `npm run build`, and then manually upload the generated `build` directory to the server casdoor/web directory.

**Comment by ffyuanda** [comment]
yeah that could work I guess

> > I have the same situation before, I think it is because the 2GB memory is not enough
> 
> You can execute `npm run build`, and then manually upload the generated `build` directory to the server casdoor/web directory.

**Comment by ffyuanda** [comment]
alright after upgraded to 4GB ram everything works out... thanks people
