### ISSUE TITLE
Google cloud storage upload does not work

### ISSUE THREAD

**Issue by jadiaheno** [casbin/casdoor#2539]
Steps to reproduce:
- Casdoor/latest on docker
- Create a google cloud storage provider with:
    - client ID: GOOG1EXXXXXXXXXXXXXXXXXXXXXXXXXXXJBS
    - client secret: bTMT0gXXXXXXXXXXXXXXXXXXXXXXXXXXXdWt/kY
    - Endpoint: https://storage.googleapis.com
    - bucket: bucket_name
- Save and exit

- Upload a resource
- Error shown in the log

```
2023-12-12 18:15:49 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd2827e]
2023-12-12 18:15:49 
2023-12-12 18:15:49 goroutine 375 [running]:
2023-12-12 18:15:49 golang.org/x/oauth2/authhandler.authHandlerSource.Token({{0x307e428, 0xc000224020}, 0xc0002e2bd0, 0x0, {0x0, 0x0}, 0x0})
2023-12-12 18:15:49     /go/pkg/mod/golang.org/x/oauth2@v0.11.0/authhandler/authhandler.go:80 +0x19e
2023-12-12 18:15:49 golang.org/x/oauth2.(*reuseTokenSource).Token(0xc000e49290)
2023-12-12 18:15:49     /go/pkg/mod/golang.org/x/oauth2@v0.11.0/oauth2.go:307 +0xd5
2023-12-12 18:15:49 golang.org/x/oauth2.(*Transport).RoundTrip(0xc00105d840, 0xc000de4100)
2023-12-12 18:15:49     /go/pkg/mod/golang.org/x/oauth2@v0.11.0/transport.go:45 +0xd6
2023-12-12 18:15:49 net/http.send(0xc000de4100, {0x3069600, 0xc00105d840}, {0x2892a80?, 0x1?, 0x0?})
2023-12-12 18:15:49     /usr/local/go/src/net/http/client.go:251 +0x5f7
2023-12-12 18:15:49 net/http.(*Client).send(0xc000e496e0, 0xc000de4100, {0xc0015bcb50?, 0x0?, 0x0?})
2023-12-12 18:15:49     /usr/local/go/src/net/http/client.go:175 +0x9b
2023-12-12 18:15:49 net/http.(*Client).do(0xc000e496e0, 0xc000de4100)
2023-12-12 18:15:49     /usr/local/go/src/net/http/client.go:715 +0x8fc
2023-12-12 18:15:49 net/http.(*Client).Do(...)
2023-12-12 18:15:49     /usr/local/go/src/net/http/client.go:581
2023-12-12 18:15:49 google.golang.org/api/internal/gensupport.send({0x307e428?, 0xc000224020}, 0x2952907?, 0xc000de4000)
2023-12-12 18:15:49     /go/pkg/mod/google.golang.org/api@v0.138.0/internal/gensupport/send.go:72 +0xf2
2023-12-12 18:15:49 google.golang.org/api/internal/gensupport.SendRequest({0x307e428, 0xc000224020}, 0x293bd5f?, 0xc000de4000)
2023-12-12 18:15:49     /go/pkg/mod/google.golang.org/api@v0.138.0/internal/gensupport/send.go:65 +0xfc
2023-12-12 18:15:49 google.golang.org/api/storage/v1.(*ObjectsInsertCall).doRequest(0xc00105e320, {0x29385b2, 0x4})
2023-12-12 18:15:49     /go/pkg/mod/google.golang.org/api@v0.138.0/storage/v1/storage-gen.go:10001 +0xa59
2023-12-12 18:15:49 google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc00105e320, {0x0?, 0xc000246738?, 0x11?})
2023-12-12 18:15:49     /go/pkg/mod/google.golang.org/api@v0.138.0/storage/v1/storage-gen.go:10013 +0x78
2023-12-12 18:15:49 cloud.google.com/go/storage.(*httpStorageClient).OpenWriter.func1()
2023-12-12 18:15:49     /go/pkg/mod/cloud.google.com/go/storage@v1.31.0/http_client.go:931 +0xa65
2023-12-12 18:15:49 created by cloud.google.com/go/storage.(*httpStorageClient).OpenWriter
2023-12-12 18:15:49     /go/pkg/mod/cloud.google.com/go/storage@v1.31.0/http_client.go:874 +0x49f
2023-12-12 18:15:50 2023/12/12 23:15:50 Starting Radius server on 0.0.0.0:1812
2023-12-12 18:16:14 2023/12/12 23:16:14 Starting Radius server on 0.0.0.0:1812
2023-12-12 18:16:48 panic: runtime error: invalid memory address or nil pointer dereference
2023-12-12 18:16:48 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd2827e]
2023-12-12 18:16:48 
2023-12-12 18:16:48 goroutine 26 [running]:
2023-12-12 18:16:48 golang.org/x/oauth2/authhandler.authHandlerSource.Token({{0x307e428, 0xc00012c020}, 0xc0002bf1f0, 0x0, {0x0, 0x0}, 0x0})
2023-12-12 18:16:48     /go/pkg/mod/golang.org/x/oauth2@v0.11.0/authhandler/authhandler.go:80 +0x19e
2023-12-12 18:16:48 golang.org/x/oauth2.(*reuseTokenSource).Token(0xc000ff9290)
2023-12-12 18:16:48     /go/pkg/mod/golang.org/x/oauth2@v0.11.0/oauth2.go:307 +0xd5
2023-12-12 18:16:48 golang.org/x/oauth2.(*Transport).RoundTrip(0xc00091cc80, 0xc000e4e100)
2023-12-12 18:16:48     /go/pkg/mod/golang.org/x/oauth2@v0.11.0/transport.go:45 +0xd6
2023-12-12 18:16:48 net/http.send(0xc000e4e100, {0x3069600, 0xc00091cc80}, {0x2892a80?, 0x1?, 0x0?})
2023-12-12 18:16:48     /usr/local/go/src/net/http/client.go:251 +0x5f7
2023-12-12 18:16:48 net/http.(*Client).send(0xc000ff9560, 0xc000e4e100, {0xc0003fcbb0?, 0x0?, 0x0?})
2023-12-12 18:16:48     /usr/local/go/src/net/http/client.go:175 +0x9b
2023-12-12 18:16:48 net/http.(*Client).do(0xc000ff9560, 0xc000e4e100)
2023-12-12 18:16:48     /usr/local/go/src/net/http/client.go:715 +0x8fc
2023-12-12 18:16:48 net/http.(*Client).Do(...)
2023-12-12 18:16:48     /usr/local/go/src/net/http/client.go:581
2023-12-12 18:16:48 google.golang.org/api/internal/gensupport.send({0x307e428?, 0xc00012c020}, 0x2952907?, 0xc000e4e000)
2023-12-12 18:16:48     /go/pkg/mod/google.golang.org/api@v0.138.0/internal/gensupport/send.go:72 +0xf2
2023-12-12 18:16:48 google.golang.org/api/internal/gensupport.SendRequest({0x307e428, 0xc00012c020}, 0x293bd5f?, 0xc000e4e000)
2023-12-12 18:16:48     /go/pkg/mod/google.golang.org/api@v0.138.0/internal/gensupport/send.go:65 +0xfc
2023-12-12 18:16:48 google.golang.org/api/storage/v1.(*ObjectsInsertCall).doRequest(0xc000e620f0, {0x29385b2, 0x4})
2023-12-12 18:16:48     /go/pkg/mod/google.golang.org/api@v0.138.0/storage/v1/storage-gen.go:10001 +0xa59
2023-12-12 18:16:48 google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc000e620f0, {0x0?, 0xc000548000?, 0x11?})
2023-12-12 18:16:48     /go/pkg/mod/google.golang.org/api@v0.138.0/storage/v1/storage-gen.go:10013 +0x78
2023-12-12 18:16:48 cloud.google.com/go/storage.(*httpStorageClient).OpenWriter.func1()
2023-12-12 18:16:48     /go/pkg/mod/cloud.google.com/go/storage@v1.31.0/http_client.go:931 +0xa65
2023-12-12 18:16:48 created by cloud.google.com/go/storage.(*httpStorageClient).OpenWriter
2023-12-12 18:16:48     /go/pkg/mod/cloud.google.com/go/storage@v1.31.0/http_client.go:874 +0x49f
```

**Comment by hsluoyz** [comment]
@jadiaheno this bug originates from: https://github.com/casdoor/oss/pull/11 and https://github.com/qor/oss/pull/16 . It seems that googlecloud.go code has bug.

**Comment by hsluoyz** [comment]
@jadiaheno can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@dilip640

**Comment by jadiaheno** [comment]
Yes i can make a PR. Give me  a day.

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin/casdoor/commit/08864686f3ccae5ff54ca50c53dacbc912b826c2

The service account JSON is like:

```json
{
  "type": "service_account",
  "project_id": "casbin",
  "private_key_id": "xxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\nxxx\n-----END PRIVATE KEY-----\n",
  "client_email": "casdoor-service-account@casbin.iam.gserviceaccount.com",
  "client_id": "10336152244758146xxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/casdoor-service-account%40casbin.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
```

![image](https://github.com/casbin/casdoor/assets/3787410/c010fe40-b786-42e6-a9b1-07a07fd69167)
